src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 */
class Property
{
    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct()
    {
        $this->created_at = new \DateTime();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }
    // nouvelle fonction pour formater le prix
    public function getFormattedPrice(  ): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }
    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }
    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Controller/PropertyController.php
<?php


namespace App\Controller;

use App\Entity\Property;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController
{

    /**
     * @var PropertyRepository
     */
    private $repository;

    /**
     * @var ObjectManager
     */
    private $em;

    public function __construct(PropertyRepository $repository, EntityManagerInterface $em)
    {
     $this->repository = $repository;
     $this->em = $em;
    }
    // Mettre a jour : object manager initialisation dans le construct et flush en bdd sur la fonction souhaitée (index)
    // Avantage : tte les entitées récup par le repo sont trackées par l'objectManager,
    // si modif le flush detecté et apparto modif en BDD


    /**
     * @Route("/biens", name="property.index")
     * @return Response
     */
    public function index() : Response
    {
        /*
        $propertiy = new Property();
        $propertiy->setTitle('mon premier bien')
            ->setPrice(200000)
            ->setRooms(4)
            ->setBedrooms(3)
            ->setDescription('Une petite description')
            ->setSurface(60)
            ->setFloor(4)
            ->setHeat(1)
            ->setCity('Lille')
            ->setAddress('bd Gambetta')
            ->setPostalCode('59000');

        //envoi bdd
        //persist et je l'envoi
        $em = $this->getDoctrine()->getManager();
        $em->persist($propertiy);
        $em->flush();
*/
// -----------------------------------------------------------
 // Aide Memoire:

        // Récupérer un bien en l'initialisant par le biai de doctrine :
/*
        $repository = $this->getDoctrine()->getRepository(Property::class);
*/

        // Méthode pour récupérer un bien :

/*        $property = $this->repository->find(1);
        dump($property);
        // champs automatiquement remplis // 1er et unique car par id
*/
/*        $property = $this->repository->findAll();
         dump($property);
        // renvoi un tableau contenant l'ensemble de mes biens
*/
/*         $property = $this->repository->findOneBy(['floor' => 4 ]);
         dump($property);
         // passer en para un tableau de critéres ex tout ceux qui sont au 4eme étages
*/
// ---------------------------------------------------------------------

        return $this->render('property/index.html.twig', [
            'current_menu' => 'properties'
        ]);
    }

    /**
     * @Route ("/biens/{slug}-{id}", name="property.show" , requirements={"slug": "[a-z0-9\-]*" })
     * @param Property $property
     * @param $slug
     * @param $id
     * @return Response
     */
    public function show(Property $property, $slug, $id) : Response
    {
        if ( $property->getSlug() !== $slug) {
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug(),
            ], 301 );
        }

        // 301 = redirection permanente
        // slug important pour référencement

        $property = $this->repository->find($id);
        return $this->render('property/show.html.twig', [
            'property' => $property,
            'current_menu' => 'properties'
        ]);
    }
}

templates/property/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Tous nos biens{% endblock %}
{% block body %}
    <div class="container mt-4">
        <h1>Voir tous nos biens</h1>
    </div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title property.title%}
{% block body %}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-8">

                </div>
                <div class="col-md-4">
                    <h1>{{ property.title }}</h1>
                    <h2>{{ property.rooms }} pièces - {{ property.surface }} m2</h2>
                    <div class="text-primary" style="font-size: 4rem; font-weight: bold;">{{ property.formattedPrice }} €</div>
                    <a href="#" class="btn btn-primary">Contacter l'agence</a>
                </div>
            </div>
            <nav class="nav nav-tabs" id="tab"></nav>
        </div>
    </div>
    <div class="container mt-4">

        <p>
            {{ property.description | nl2br }}
        </p>

        <div class="row">
            <div class="col-md-8">
                <h2 class="mr-5">Caractéristiques :</h2>
                   <table class="table table-striped">
                       <tr>
                           <td>Surface habitable</td>
                           <td>{{ property.surface }} m2 </td>
                       </tr>
                       <tr>
                           <td>Pièces</td>
                           <td>{{ property.rooms }}</td>
                       </tr>
                       <tr>
                           <td>Chambres</td>
                           <td>{{ property.bedrooms }}</td>
                       </tr>
                       <tr>
                           <td>Etages</td>
                           <td>{{ property.floor }}</td>
                       </tr>
                       <tr>
                           <td>Chauffage</td>
                           <td>{{ property.heatType }}</td>
                       </tr>
                   </table>
                </div>
            <div class="col-md-4">
                <h2>Spécificités</h2>
            </div>
        </div>
    </div>

{% endblock %}